version: "3.8"

services: 
  rest-api:
    build:
      context: ../
      dockerfile: RestApi/Dockerfile
    ports:
      - "8080:80"
    networks: 
      - hc-network

  hc-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks: 
      - hc-network
networks:
  hc-network:
    name: hc-network